# This is a boilerplate parameters config generated for pipeline 'deep_learning_interpolation'
# using Kedro 0.18.4.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.4/kedro_project_setup/configuration.html#parameters

deep_learning_model:
    ext: 0.01
    grid_length: 10
    exp_var: 0.95
    past_data_range: 5
    column_order: ['id', 'observationDateTime', 'deviceStatus', 'airQualityLevel',              'aqiMajorPollutant', 'airQualityIndex', 'co.avgOverTime',                   'pm10.avgOverTime', 'pm2p5.avgOverTime', 'co2.avgOverTime',
                    'so2.avgOverTime', 'no2.avgOverTime', 'o3.avgOverTime',
                    'uv.avgOverTime', 'airTemperature.avgOverTime',
                    'atmosphericPressure.avgOverTime','illuminance.avgOverTime',
                    'relativeHumidity.avgOverTime', 'ambientNoise.avgOverTime']
    monitor: 'loss'
    mode: 'min'
    activation_function: 'relu'
    learning_rate: 0.0001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 0.0000001
    name: 'Nadam'
    metric: 'Accuracy'
    batch_size: 4
    epochs: 5
    intr_batch_size: 128
